// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
/// 
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrg1WeE1bYYNQRUto8rEjw0tHmxrUl37g',
    appId: '1:209944295694:web:4b9407243e2adf6693ff5f',
    messagingSenderId: '209944295694',
    projectId: 'err50-75cc3',
    authDomain: 'err50-75cc3.firebaseapp.com',
    storageBucket: 'err50-75cc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmiAPXUzlgkJ-wKJeP-k2LRu0vxJpnwOs',
    appId: '1:209944295694:android:8fa832d0af32df4e93ff5f',
    messagingSenderId: '209944295694',
    projectId: 'err50-75cc3',
    storageBucket: 'err50-75cc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7WOAy72XjFAvuDE8KTYQUNMz_Q2lTJWA',
    appId: '1:209944295694:ios:7d4a11c0a234563793ff5f',
    messagingSenderId: '209944295694',
    projectId: 'err50-75cc3',
    storageBucket: 'err50-75cc3.appspot.com',
    iosClientId: '209944295694-vismiul226919cl38cnum4s6g7bokqn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.hirecruit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7WOAy72XjFAvuDE8KTYQUNMz_Q2lTJWA',
    appId: '1:209944295694:ios:7d4a11c0a234563793ff5f',
    messagingSenderId: '209944295694',
    projectId: 'err50-75cc3',
    storageBucket: 'err50-75cc3.appspot.com',
    iosClientId: '209944295694-vismiul226919cl38cnum4s6g7bokqn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.hirecruit',
  );
}
